#!/bin/bash

# Ensure Homebrew is updated
brew update

# Install system dependencies with Homebrew
brew install libffi openssl

# Check if Python 3 is installed
if ! command -v python3 &> /dev/null; then
    echo "Python 3 could not be found, attempting to install."
    brew install python
else
    echo "Python 3 is already installed."
    python3_version=$(python3 --version | grep -oP 'Python \K([0-9]+\.[0-9]+)')
    echo "Python version: $python3_version"
fi

# Uninstall Fabric if it's already installed (pip3 comes with Python 3)
pip3 freeze | grep Fabric && pip3 uninstall -y Fabric

# Install Python package dependencies with pip3
pip3 install pyparsing
pip3 install appdirs
pip3 install "setuptools==40.1.0"
pip3 install "cryptography==2.8"
pip3 install "bcrypt==3.1.7"
pip3 install "PyNaCl==1.3.0"
pip3 install "Fabric3==1.14.post1"

echo "Fabric and dependencies installation complete."

